config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  root 'products#index'
  devise_for :users
  get 'welcome/index'
  get 'static/about', :as => 'about_page'
  resources :product_items
  resources :ingridients
  resources :types
  resources :categories
  resources :products
  resources :brands

  resources :categories do
    resources :products
  end

  resources :brands do
    resources :products
  end

  resources :products do
    resources :reviews, except: [:show, :index]
  end

  resources :products, only: [:index, :new, :create, :update]

  get "/:page" => "static#show"
end

app/models/ingridient.rb
class Ingridient < ApplicationRecord
  has_many :product_ingridients
  has_many :products, through: :product_ingridients

  validates :name, uniqueness: true
end

app/controllers/ingridients_controller.rb
class IngridientsController < ApplicationController
  before_action :set_ingridient, only: [:show, :edit, :update, :destroy]

  # GET /ingridients
  # GET /ingridients.json
  def index
    @ingridients = Ingridient.all
  end

  # GET /ingridients/1
  # GET /ingridients/1.json
  def show
  end

  # GET /ingridients/new
  def new
    @ingridient = Ingridient.new
  end

  # GET /ingridients/1/edit
  def edit
  end

  # POST /ingridients
  # POST /ingridients.json
  def create
    @ingridient = Ingridient.new(ingridient_params)

    respond_to do |format|
      if @ingridient.save
        format.html { redirect_to @ingridient, notice: 'Ingridient was successfully created.' }
        format.json { render :show, status: :created, location: @ingridient }
      else
        format.html { render :new }
        format.json { render json: @ingridient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingridients/1
  # PATCH/PUT /ingridients/1.json
  def update
    respond_to do |format|
      if @ingridient.update(ingridient_params)
        format.html { redirect_to @ingridient, notice: 'Ingridient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingridient }
      else
        format.html { render :edit }
        format.json { render json: @ingridient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingridients/1
  # DELETE /ingridients/1.json
  def destroy
    @ingridient.destroy
    respond_to do |format|
      format.html { redirect_to ingridients_url, notice: 'Ingridient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingridient
      @ingridient = Ingridient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingridient_params
      params.require(:ingridient).permit(:name, :description)
    end
end

app/helpers/ingridients_helper.rb
module IngridientsHelper
end

app/views/ingridients/_form.html.erb
<%= form_with(model: ingridient, local: true) do |form| %>
  <% if ingridient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingridient.errors.count, "error") %> prohibited this ingridient from being saved:</h2>

      <ul>
        <% ingridient.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, 'Название' %>
    <%= form.text_field :name, class:"enter-name" %>
  </div>

  <div class="field">
    <%= form.label :description, 'Описание' %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit "Добавить", class: "A_Button" %>
  </div>
<% end %>

app/views/ingridients/edit.html.erb
<h1>Editing Ingridient</h1>

<%= render 'form', ingridient: @ingridient %>

<%= link_to 'Show', @ingridient %> |
<%= link_to 'Back', ingridients_path %>

app/views/ingridients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ингридиенты</h1>

<section class="ingridient-list">
  <% @ingridients.each do |ingridient| %>
    <div class="ingridient-card">
      <h3><%= ingridient.name %></h3>
      <p><%= ingridient.description %></p>
      <a><%= link_to 'Подробнее', ingridient %></a>
    </div>
  <% end %>
</section>

<br>

<%= link_to 'New Ingridient', new_ingridient_path %>

app/views/ingridients/new.html.erb
<h1>Добавить ингридиент</h1>

<%= render 'form', ingridient: @ingridient %>

<%= link_to 'Back', ingridients_path %>

app/views/ingridients/show.html.erb
<p id="notice"><%= notice %></p>

<section class ="ingridient-page">
  <h1>
    <%= @ingridient.name %>
  </h1>

  <p>
    <%= @ingridient.description %>
  </p>
</section>

<%= link_to 'Edit', edit_ingridient_path(@ingridient) %> |
<%= link_to 'Back', ingridients_path %>