config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  root 'products#index'
  devise_for :users
  get 'welcome/index'
  get 'static/about', :as => 'about_page'
  resources :product_items
  resources :ingridients
  resources :types
  resources :categories
  resources :products
  resources :brands

  resources :categories do
    resources :products
  end

  resources :brands do
    resources :products
  end

  resources :products do
    resources :reviews, except: [:show, :index]
  end

  resources :products, only: [:index, :new, :create, :update]

  get "/:page" => "static#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products

  validates :name, uniqueness: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name, uniqueness: true
end

app/models/ingridient.rb
class Ingridient < ApplicationRecord
  has_many :product_ingridients
  has_many :products, through: :product_ingridients

  validates :name, uniqueness: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :brand, :optional => true
  belongs_to :type
  has_many :product_items
  has_many :favourite_items
  has_many :reviews

  has_and_belongs_to_many :ingridients

  validates :name, uniqueness: true

  has_attached_file :image, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
  end
end

app/models/product_ingridient.rb
class ProductIngridient < ApplicationRecord
  belongs_to :ingridient
  belongs_to :product
end

app/models/product_item.rb
class ProductItem < ApplicationRecord
  belongs_to :product
  belongs_to :ingridient
  has_many :favourite_items
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :products
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :password, presence: true
  validates :email, presence: true
  validates :username, presence: true

  def favorite(product)
    favorites.find_or_create_by(product: product)
  end

  def unfavorite(product)
    favorites.where(product: product).destroy_all

    product.reload
  end

  def favorited?(product)
    favorites.find_by(product_id: product.id).present?
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all
    @products = Product.all
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
    @brand = Brand.find(params[:id])
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def brand_params
      params.require(:brand).permit(:name, :product_id)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def show
    render params[:page]
  end
end  

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  # GET /types
  # GET /types.json
  def index
    @types = Type.all
  end

  # GET /types/1
  # GET /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_params
      params.require(:type).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/ingridients_helper.rb
module IngridientsHelper
end

app/helpers/product_items_helper.rb
module ProductItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper

  def count_products_by_ingridient(ingridient, product)
    product_items = ingridient.product_items.where(product_id: product.id)

    [
      ingridient.name,
      ', ',
    ].join()
  end

  def style_color(product_type)
    case product_type
    when '🍒Подходит веганам'
      'vegan'
    when '🍟Подходит вегетарианцам'
      'vegetarian'
    else
      'non-vegetarian'
    end
  end

  def ingridient_name(product)
    product.ingridients.map { |ingridient| ingridient.name }
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/types_helper.rb
module TypesHelper

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/brands/_form.html.erb
<%= form_with(model: brand, local: true) do |form| %>
  <% if brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
        <% brand.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, 'Название' %>
    <%= form.text_field :name, class:"enter-name" %>
  </div>

  <div class="actions">
    <%= form.submit "Добавить", class: "A_Button" %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Редактировать бренд</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Brands</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.name %></td>
        <td><%= brand.product_id %></td>
        <td><%= link_to 'Show', brand %></td>
        <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
        <td><%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brand', new_brand_path %>

app/views/brands/new.html.erb
<h1>Добавить производителя</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="brand-name">
  Продукты от <%= @brand.name %>
</h1>

<section class="brand-page">
  <div class="product-list">
    <% @brand.products.each do |product| %>
    <% id = product.brand_id %>
    <% brand = Brand.find_by id: id %>


    <% id = product.type_id %>
    <% type = Type.find_by id: id %>

      <div class="product-card">
        <div class="card-image"><%= image_tag product.image.url %></div>
        <p><%= link_to product.name, brand_product_path(product.category, product) %></p>
      </div>
    <% end %>
  </div>
</section>

<!-- <p>
  <strong>Product:</strong>
  <%#= @brand.product_id %>
</p> -->

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>