config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  root 'products#index'
  devise_for :users
  get 'welcome/index'
  get 'static/about', :as => 'about_page'
  resources :product_items
  resources :ingridients
  resources :types
  resources :categories
  resources :products
  resources :brands

  resources :categories do
    resources :products
  end

  resources :brands do
    resources :products
  end

  resources :products do
    resources :reviews, except: [:show, :index]
  end

  resources :products, only: [:index, :new, :create, :update]

  get "/:page" => "static#show"
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :brand, :optional => true
  belongs_to :type
  has_many :product_items
  has_many :favourite_items
  has_many :reviews

  has_and_belongs_to_many :ingridients

  validates :name, uniqueness: true

  has_attached_file :image, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @categories = Category.all
    @products = Product.search(params[:search])
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @reviews = Review.where(product_id: @product.id).order("created_at DESC")
      if @reviews.blank?
        @avg_review = 0
      else
        @avg_review = @reviews.average(:rating).round(2)
      end
  end


  # GET /products/new
  def new
    @product = Product.new

    if params[:category_id]
      @product.category_id = params[:category_id]
    end
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    #с помощью этого метода параметры идут на сервер, а потом обрабатываются

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:category_id, :type_id, :brand_id, :name,  :description, :image, ingridient_ids: [])
    end
end

app/helpers/products_helper.rb
module ProductsHelper

  def count_products_by_ingridient(ingridient, product)
    product_items = ingridient.product_items.where(product_id: product.id)

    [
      ingridient.name,
      ', ',
    ].join()
  end

  def style_color(product_type)
    case product_type
    when '🍒Подходит веганам'
      'vegan'
    when '🍟Подходит вегетарианцам'
      'vegetarian'
    else
      'non-vegetarian'
    end
  end

  def ingridient_name(product)
    product.ingridients.map { |ingridient| ingridient.name }
  end
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category_id, 'Категория' %>
    <br>
    <%= form.select :category_id, Category.all.collect { |c| [c.name, c.id] } %>
    <div class="select-arrow"></div>
  </div>

  <div class="field">
    <%= form.label :name, 'Название продукта' %>
    <br>
    <%= form.text_field :name, class:"enter-name" %>
  </div>

  <div class="field">
    <%= form.label :brand_id, 'Производитель' %>
    <br>
    <%= form.select :brand_id, Brand.all.collect { |b| [b.name, b.id] }, :include_blank => true %>
    <div class="select-arrow"></div>
  </div>

  <div class="field">
    <%= form.label :type_id, 'Тип продукта' %>
    <br>
    <%= form.select :type_id, Type.all.collect { |t| [t.name, t.id] } %>
    <div class="select-arrow"></div>
  </div>

  <div class="field">
    <%= form.label :ingridient_ids, 'ПЖП', class:"ingridient-form" %>
    <br>
    <%= form.collection_check_boxes(:ingridient_ids, Ingridient.all, :id, :name) do |b| %>
        <%= b.label class:"label-checkbox" do%>
          <%=b.check_box + b.text %>
          <br>
        <%end%>
    <% end %>
    <%#= form.collection_check_boxes :ingridient_ids, Ingridient.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :description, 'Состав' %>
    <br>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image, 'Фотография' %>
    <br>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit "Сохранить", class: "A_Button" %>
  </div>


<% end %>

app/views/products/_product.html.erb
<p>
<strong>Name:</strong>
<%= product.name %>
</p>

<p>
<strong>Description:</strong>
<%= product.description %>
</p>

<% if controller_name == 'categories' %>
  <%= link_to 'Показать', category_product_path(product.category) %>
  <%= link_to 'Редактировать продукт', edit_category_product_path(product.category) %>
<% else %>
  <%= link_to 'Показать', product_path(product) %>
  <%= link_to 'Редактировать продукт', edit_product_path(product) %>
<% end %>

app/views/products/edit.html.erb
<h1 class="edit-product">Редактировать продукт</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |

<% if params[:category_id] %>
  <%= link_to 'Back', category_path(params[:category_id]) %>
<% else %>
  <%= link_to 'Back', products_path %>
<% end %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<section class="catalog-page">
  <%= render "categories/catalog" %>

  <div class="product-list">
      <% @products.each do |product| %>
      <% id = product.category_id %>
      <% category = Category.find_by id: id %>


      <% id = product.type_id %>
      <% type = Type.find_by id: id %>

      <div class="product-card">
        <div class="card-image"><%= image_tag product.image.url %></div>
        <p><%= link_to product.name, category_product_path(product.category, product) %></p>
      </div>
    <% end %>
  </div>


</section>

<br>

<!-- <div class="tabs">

   <div class="tab">
       <input type="radio" id="tab-1" name="tab-group-1" checked>
       <label for="tab-1">Tab One</label>
       <div class="content">

       </div>
   </div>

   <div class="tab">
       <input type="radio" id="tab-2" name="tab-group-1">
       <label for="tab-2">Tab Two</label>
       <div class="content">
       </div>
   </div>

</div> -->

app/views/products/new.html.erb
<h1>Добавить продукт</h1>

<%= render 'form', product: @product %>
<br>
<% if params[:category_id] %>
  <%#= link_to 'Back', category_path(params[:category_id]) %>
<% else %>
  <%#= link_to 'Back', products_path %>
<% end %>

app/views/products/show.html.erb
<%= content_for :header do %>
<% end %>

<p id="notice"><%= notice %></p>

<section class="product-page">
  <div class="about-product">
    <h1>
      <%= @product.name %>
    </h1>

    <% if @product.brand %>
      <a class="link-to-brand">
        Производитель:
        <%= link_to @product.brand.name, brand_path(@product.brand, @brand) %>
      </a>
    <% end %>

    <h3 class=<%= style_color(@product.type.name)%>>
        <%= @product.type.name %>
    </h3>


    <p>
      <strong>ПЖП:</strong>
      <% if @product.ingridients.count > 0 %>
        <%= ingridient_name(@product).join(', ') %>
      <% else %>
        <span class="no-ingridients">Отсутствуют ✓</span>
      <% end %>
    </p>

    <p>
      <strong>Состав:</strong>
      <%= @product.description %>
    </p>

    <%#= link_to 'About', categories_path, class: "A_Button" %>

    <%= link_to image_tag("icons/edit.png"), edit_category_product_path(@product.category, @product) %>
    <%#= link_to 'Back', products_path %>

    <hr>
  </div>

  <div class="product-image"><%= image_tag @product.image.url %></div>
</section>

<section class="reviews">
  <div class="adding-review">
    <h2>Отзывы</h2>
    <div class="star-rating" data-score= <%= @avg_review %> ></div>
    <div class="A_Button"><%= link_to "Написать отзыв", new_product_review_path(@product) %></div>
  </div>

  <div class="review-list">
    <% if @reviews.blank? %>
      <h3>У этого продукта пока нет отзывов. Ваш будет первым :)</h3>
    <% else %>
      <% @reviews.each do |review| %>
        <div class="review">
          <h3><%= current_user.username %></h3>
          <div class="star-rating" data-score= <%= review.rating %> ></div>
          <p><%= review.comment %></p>
        </div>
      <% end %>
    <% end %>
  </div>
</section>

<script>
  $(document).ready(function() {
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
    });
  });
</script>